# Python 기초 문법

### 주요 내용

1. int, str 등 주요 객체 형식
2. 리스트와 튜플, 딕셔너리의 이해
3. numpy를 활용한 행렬 연산

<br>

### 목표 
1. int, str 등 객체 형식에 따라 적절한 메서드를 활용한다.
2. 여러 개의 값을 리스트 형식 등으로 저장하고 활용한다.
3. 리스트와 튜플, 딕셔너리의 차이를 이해한다.


<br>
<hr>
<br>

> Python은 개발 언어로 분석 중심의 언어가 아닙니다. 0에서 1을 만드는 개발과 달리 데이터 분석은 데이터라는 재료를 활용하기 때문에 방대한 Python 기초 문법을 모두 배워야하는 것은 아닙니다. 필요하고 중요한 내용 중심으로 살펴보겠습니다.


<br>

## 1. 형식의 이해



<br>



### 1.1. 숫자와 문자, 출력과 저장(할당)

숫자는 그냥 입력하면 되고, 문자는 큰 따옴표나 작은 따옴표를 붙임  
`print( )` 함수를 써서 출력하거나 `=`을 써서 값을 객체로 저장할 수도 있음

In [19]:
# 숫자와 연산
    ## 마지막 결과만 출력
    ## 중간 공백은 문제 없지만 시작 위치는 민감
print(1+2*3/4)

print(1 + 2  * 3/4**5)

2.5
1.005859375


In [5]:
# 문자
    ## 큰따옴표, 작은따옴표 차이 없음
'삼성전자'

'삼성전자'

In [7]:
"삼성전자"

'삼성전자'

In [8]:
"작은따옴표(' ')를 포함한 글자"

"작은따옴표(' ')를 포함한 글자"

In [10]:
# 할당(assign), 저장
    ## '+' : 숫자 덧셈 연산, 문자열 결합
a = '가나다'
b = '라마바'

a+b

'가나다라마바'

In [11]:
# 업데이트
c = 0
c = 1
c

1

In [17]:
# 자기 자신을 활용한 업데이트
#c = c + 10

c += 100  
    ## c += 100 : c = c + 100
c

421

In [23]:
# print( )를 활용한 출력
    ## 숫자나 문자를 콤마(,)로 나열하면 출력
    ## 함수 안에서 Shift + Tab 눌러 도움말 보기

print('삼성전자')
print('DS', 'DX', "test", 100, c, c+100)

삼성전자
DS DX test 100 421 521


In [25]:
# 문자열의 f-string 메서드를 활용한 출력
    ## 콤마로 나열할 필요 없이 문자열 중간에 값을 넣어 출력 가능    

x=110
y=999

print('x는 {}이고, y는 {}이다'.format(x, y)) # 과거에 주로 활용

x는 110이고, y는 999이다


In [27]:
print(f'x는 {x}이고, y는 {y+x}이다') # 최근에 주로 활용

x는 110이고, y는 1109이다


#### [실습] x에 10.1을 저장하고, y에 101을 저장한 다음 더하기

In [28]:
x = 10.1
y = 101
x+y

111.1

#### [실습] a=1, b=5로 할당하고 문자 'a + b는'과 a+b 계산 결과를 print( )로 함께 출력

출력 결과 예시  
`1 + 5는 6`

In [30]:
a=1
b=5

print(f"{a} + {b}는 {a+b}")

1 + 5는 6


<br>

#### [참고] print를 활용한 로그 저장

In [35]:
from datetime import datetime


with open('log.txt', 'w') as f:
    time1 = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f'{time1} - 점심먹고왔음.', file=f)



<br>
<br>

### 1.2. type( )을 활용한 데이터 타입(type, 형식) 확인 

`type( )`을 활용해서 각 데이터, 객체(object)의 타입을 확인

* int : 정수(integer)
* str : 문자열(string)
* float : 소수점, 비율을 포함한 실수


In [36]:
type(1)

int

In [37]:
type('가')

str

In [38]:
type('1')

str

In [39]:
type(1.0)

float

<br>

### 1.3.  비교 연산과 bool 형식의 이해
등호와 부등호를 활용해서 숫자를 비교(비교 연산)
`=`은 할당(저장)을 할 때 활용되므로 일치여부를 확인할 때는 `==`을 활용하고 불일치여부는 `!=`을 활용  

비교 연산 등의 결과로 **True** 혹은 **False**가 출력되는데 이렇게 참, 거짓 두개의 값을 갖는 객체는 *불(bool)* 형식으로 저장

In [42]:
x=10
y=99

In [43]:
x>=y

False

In [44]:
y==9

False

In [45]:
y!=9

True

In [46]:
type(y>0)

bool


<br>

## 2. 여러 값을 묶은 리스트(list)

`1`, `'삼성'`처럼 하나의 값이 아니라 여러개의 값을 묶으면 수열, 문자열이 생성  
Python에서는 **리스트(list)** 형식 등으로 수열, 문자열을 다룸  


### 2.1. 대괄호([ ])를 활용한 리스트 생성

In [47]:
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [48]:
# 타입 확인 : list
type(salary)

list

In [53]:
# 문자열 리스트
jobs = ['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리', [5000, 6000]    ]
(jobs)

['회로설계',
 '반도체공정설계',
 '신호 및 시스템 설계',
 'S/W개발',
 '영업마케팅',
 '경영지원',
 '생산관리',
 [5000, 6000]]

#### [실습] 1~45까지 숫자 중에서 마음대로 6개 숫자 선택해서 리스트로 만들어 저장하기



#### [실습] 점심/저녁 메뉴 3개를 리스트로 묶어 menu로 저장하기 



In [55]:
numList = [7, 9, 44, 11, 15, 21]
numList

[7, 9, 44, 11, 15, 21]

In [56]:
menu = ["coffee", "latte", "long black"]

<br>

### 2.2. 리스트의 주요 메서드

append( )는 리스트에 값을 추가하고, extend( )는 리스트에 또다른 리스트를 이어 붙임

In [57]:
# 리스트 만들기
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [59]:
# 리스트에 항목 하나 추가하기
salary.append(10000)
salary

[5000, 6000, 7000, 6000, 9000, 10000, 10000]

In [60]:
# 또다른 리스트를 이어 붙이기
salary.extend([6000, 5000])
salary

[5000, 6000, 7000, 6000, 9000, 10000, 10000, 6000, 5000]

In [61]:
b = [5500, 6500]
salary.extend(b)
salary

[5000, 6000, 7000, 6000, 9000, 10000, 10000, 6000, 5000, 5500, 6500]

#### [실습] 관심있는 메뉴 3개를 묶은 menu에 append( )로 메뉴 하나 더 추가하기



In [62]:
print(menu)
menu.append("ramen")
print(menu)

['coffee', 'latte', 'long black']
['coffee', 'latte', 'long black', 'ramen']


<br>

## 2.3. index의 활용   

리스트를 만들 때 사용한 대괄호와 별개로, 만들어진 리스트에 대괄호 인덱스를 활용해서 부분을 선택



In [66]:
salary

[5000, 6000, 7000, 6000, 9000, 10000, 10000, 6000, 5000, 5500, 6500]

In [68]:
# 대괄호 index를 활용한 부분 선택
    ## index는 0부터 시작 : 첫번째 값이 0
    ## 콜론(:)을 활용해 연속적인 인덱스 지정 가능(슬라이싱), 끝 인덱스 미포함
salary[-2]

5500

In [73]:
salary[:]

[5000, 6000, 7000, 6000, 9000, 10000, 10000, 6000, 5000, 5500, 6500]

In [75]:
# 인덱스를 활용한 업데이트
salary[5] = 50000
salary

[50000, 6000, 7000, 6000, 9000, 50000, 10000, 6000, 5000, 5500, 6500]

#### [실습] menu에서 첫번째 메뉴만 선택


#### [실습] menu에서 세번째 메뉴를 '우동'으로 변경



In [78]:
menu[2] = "udon"

In [79]:
menu

['coffee', 'latte', 'udon', 'ramen']

### 2.4. 다양한 리스트 생성 방법
<br> 

#### 2.4.1. list( )의 활용

list( )로 빈 리스트를 만들거나 다른 타입의 값들을 리스트 형식으로 변환

In [80]:
a = list()
print(a)

a.append('2023-12-25')
print(a)

a.append('2023-12-31')
print(a)


[]
['2023-12-25']
['2023-12-25', '2023-12-31']





#### 2.4.2. range( )를 활용한 수열 만들기

연속적인 수열을 만들 때는 range( )를 활용


In [81]:
# 0부터 시작하는 range
range(10)

range(0, 10)

In [82]:
# range( )와 list( )를 활용한 수열 생성
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [83]:
list(range(1, 20))
    ## 1부터 20 바로 앞 19까지

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [84]:
list(range(1, 20, 3))
    ## 1부터 19까지 3간격

[1, 4, 7, 10, 13, 16, 19]

#### [실습] range( )와 list( )로 2013부터 2022까지 10개 연도 만들기




In [85]:
list( range( 2013, 2023 )  )

[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

<br>

## 3. 여러 값을 묶은 튜플(tuple)과 딕셔너리(Dictionary)

<br>

### 3.1. 튜플

> 리스트와 비슷하게 여러개의 값을 묶지만, 값 변경이 불가능해서 데이터 분석에서 활용도는 떨어집니다. 다만, 전체 분석과정에서 절대 바뀌지 않는 값 묶음이 있다면, 튜플 형식을 활용할 수 있습니다.  

튜플은 소괄호를 활용해서 만들 수 있고, 소괄호는 생략 가능



In [87]:
aa = (1, 2, 3)
bb = '아침', '점심', '저녁'

print(type(aa))
print(bb)

<class 'tuple'>
('아침', '점심', '저녁')


In [88]:
# 인덱스 활용 가능
print(aa[0])
print(bb[1:])

1
('점심', '저녁')


In [89]:
# 추가/업데이트 불가능
aa[0] = 4

TypeError: 'tuple' object does not support item assignment

### 3.2. 딕셔너리

딕셔너리는 **키(key)** 와 **값(value)** 을 연결한 **쌍** 을 활용해서 여러 값을 구분해서 저장  

딕셔너리는 중괄호 `{ }`를 활용하고 아래와 같은 방법으로 생성합니다. 

```[Python]
{'key1':'value1', 'key2':'value2', 'key3':'value3', ...}
```

> 리스트가 `연봉`처럼 여러 관측치의 동일한 속성을 저장한다면, 딕셔너리는 하나의 대상에 대해서 키라고 부르는 여러 속성의 값을 저장합니다.   


In [90]:
# 이 강의의 속성을 딕셔너리로 저장
this_lecture = {'회사':'삼성전자', '분석도구':'Python', '기간':'3일'}
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '기간': '3일'}

In [91]:
# 대괄호와 키를 활용한 선택
    ## 리스트의 인덱스 대신 키를 활용
this_lecture['회사']

'삼성전자'

In [92]:
# 메서드 get()을 활용한 선택
this_lecture.get('회사')

'삼성전자'

In [93]:
# 쌍 추가 
this_lecture['수강인원'] = 20
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '기간': '3일', '수강인원': 20}

In [95]:
this_lecture[10] = 20
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '기간': 3, '수강인원': 20, 10: 20}

In [97]:
this_lecture[0]

KeyError: 0

In [98]:
# 쌍 제거
del this_lecture['기간']
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '수강인원': 20, 10: 20}

In [101]:
# 키 목록 선택
(this_lecture.keys())

dict_keys(['회사', '분석도구', '수강인원', 10])

In [102]:
# 리스트 형식으로 변환
list(this_lecture.keys())

['회사', '분석도구', '수강인원', 10]

In [103]:
# 값 목록 선택
this_lecture.values()

dict_values(['삼성전자', 'Python', 20, 20])

#### [실습] 각자 본인의 아래 정보를 딕셔너리로 저장

(딕셔너리의 값(value)에 리스트를 넣는 것도 가능)

* 이름
* 부서
* 연차
* 관심메뉴(위에서 만든 menu를 값으로 지정)



In [105]:
my_info = {"부서":"Research", "연차": 8, "관심메뉴":menu}
my_info

{'부서': 'Research', '연차': 8, '관심메뉴': ['coffee', 'latte', 'udon', 'ramen']}

In [106]:
my_info["이름"] = "박종현"
my_info

{'부서': 'Research',
 '연차': 8,
 '관심메뉴': ['coffee', 'latte', 'udon', 'ramen'],
 '이름': '박종현'}

In [108]:
my_info2 = {"이름":"박종현", "부서":"Research", "연차": 8, "관심메뉴":menu}
my_info2

{'이름': '박종현',
 '부서': 'Research',
 '연차': 8,
 '관심메뉴': ['coffee', 'latte', 'udon', 'ramen']}

In [109]:
my_info == my_info2

True

<br>

## 4. 흐름 제어문의 활용

### 4.1. if 조건문  

**if** 를 활용하여 특정한 상황에서만 명령어를 실행 가능  
**else**나  **elif**를 추가로 활용 가능  

In [125]:
# if의 활용
score=10

if (score >=80) :
    print('합격')
    print('축하합니다!')

In [113]:
# if와 else의 활용
score=100

if score >=80:
    print('합격')
else:
    print('탈락')

합격


In [116]:
# if와 elif와 else의 활용
score = 50 # 결측

if score is None:
    print('미응시')
elif score >=80:
    print('합격')
else:
    print('탈락')

탈락


<br>

### 4.2. for 반복문
**for**는 반복 대상을 지정하고 특정한 명령을 반복 실행

In [126]:
# 간단한 for 예제
count = 0

for i in [11,12,13]:
    count += 1 ## 반복할 때마다 1씩 증가    
    print(f'{count}번째 값은 {i}')

1번째 값은 11
2번째 값은 12
3번째 값은 13


In [127]:
count

3

In [128]:
# for문 안에서 if문을 활용
m2 = []

for a in range(1,101):
    if a % 7 ==0: # 7로 나눈 나머지가 0이면
        m2.append(a)


In [129]:
m2

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]

#### [ 참고] []와 for, if의 활용

리스트를 만드는 [] 안에서 for와 if를 활용할 수도 있음

In [130]:
[x for x in range(1,101) if x%7==0]

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]

<br>

#### [실습]

1. 구구단 19단 출력하기  
`19 X 1 = 19`  
`19 X 2 = 38 ... ` 

2. 아래의 숫자 리스트 *x* 에서 10 이상인 숫자만 따로 모아 합계 계산하기


In [ ]:
#1. 참고
print(f'{19} X {1} = {19}')

In [138]:
for i in range(1, 10):
    for j in range(1,10):
        print(f'{j}X{i}={j*i}', end="\t")
    print("")

1X1=1	2X1=2	3X1=3	4X1=4	5X1=5	6X1=6	7X1=7	8X1=8	9X1=9	
1X2=2	2X2=4	3X2=6	4X2=8	5X2=10	6X2=12	7X2=14	8X2=16	9X2=18	
1X3=3	2X3=6	3X3=9	4X3=12	5X3=15	6X3=18	7X3=21	8X3=24	9X3=27	
1X4=4	2X4=8	3X4=12	4X4=16	5X4=20	6X4=24	7X4=28	8X4=32	9X4=36	
1X5=5	2X5=10	3X5=15	4X5=20	5X5=25	6X5=30	7X5=35	8X5=40	9X5=45	
1X6=6	2X6=12	3X6=18	4X6=24	5X6=30	6X6=36	7X6=42	8X6=48	9X6=54	
1X7=7	2X7=14	3X7=21	4X7=28	5X7=35	6X7=42	7X7=49	8X7=56	9X7=63	
1X8=8	2X8=16	3X8=24	4X8=32	5X8=40	6X8=48	7X8=56	8X8=64	9X8=72	
1X9=9	2X9=18	3X9=27	4X9=36	5X9=45	6X9=54	7X9=63	8X9=72	9X9=81	


In [140]:
#2. 
x = [9, 10, 4, 22, 3, 19]

In [141]:
total = 0

for e in x:
    if e >= 10:
        total +=e
        
print(total)

51


In [146]:
sum([e for e in x if e>=10])

51

<br>

## 5. numpy의 활용 

**numpy**는 *ndarray*라는 형식을 활용해서 다양한 행렬 연산과 처리를 지원

In [147]:
import numpy as np

In [148]:
x = [1, 2, 4, 8]
y = np.array(x)
y

array([1, 2, 4, 8])

In [149]:
y2 = np.array([ [1,2,3,4], [9,8,7,6] ])
y3 = np.array([ [0, 1], [1, 0] ])

y2, y3              

(array([[1, 2, 3, 4],
        [9, 8, 7, 6]]),
 array([[0, 1],
        [1, 0]]))

In [150]:
# 산술 연산
y2 * 2 + 1

array([[ 3,  5,  7,  9],
       [19, 17, 15, 13]])

In [151]:
# 행렬 곱
y3@y2

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [152]:
# 행렬 크기 확인
y2.shape

(2, 4)

#### End of script